export default [
  { name: "Alan Roybal", team: "Director", image: "ALAN_ROYBAL.JPG" },
  { name: "Veer Shah", team: "Director", image: "VEER_SHAH.jpg" },
  { name: "Dhivyesh Prithiviraj", team: "Marketing Lead", image: "DHIVYESH_PRITHIVIRAJ.JPG" },
  { name: "Danish Ejaz", team: "Marketing", image: "DANISH_EJAZ.JPG" },
  { name: "Lisa Lupeitu'u", team: "Marketing", image: "LISA_LUPEITUU.JPG" },
  { name: "Santiago Islas", team: "Marketing", image: "SANTIAGO_ISLAS.JPG" },
  { name: "Saran Jacob", team: "Marketing", image: "SARAN_JACOB.JPG" },
  { name: "Shiloh Asir", team: "Marketing", image: "SHILOH_ASIR.JPG" },
  { name: "Shraddha Subash", team: "Marketing", image: "SHRADDHA_SUBASH.JPG" },
  { name: "Ann Jayan", team: "Marketing", image: "ANN_JAYAN.JPG" },
  { name: "Karan Jatoth", team: "Marketing", image: "KARAN_JATOTH.JPG" },
  { name: "Sristi Srinivasan", team: "Marketing", image: "SRISTI_SRINIVASAN.JPG" },
  { name: "Andrea Alvidres", team: "Marketing", image: null },
  { name: "Sachi Hansalia", team: "Industry Lead", image: "SACHI_HANSALIA.JPG" },
  { name: "Ishita Saran", team: "Industry", image: "ISHITA_SARAN.JPG" },
  { name: "Kavin Sankar", team: "Industry", image: "KAVIN_SANKAR.JPG" },
  { name: "Monish Mehta", team: "Industry", image: "MONISH_MEHTA.JPG" },
  { name: "Nandini Paidesetty", team: "Industry", image: "NANDINI_PAIDESETTY.JPG" },
  { name: "Sahas Sharma", team: "Industry", image: "SAHAS_SHARMA.JPG" },
  { name: "Sheryl Gerald", team: "Industry", image: "SHERYL_GERALD.JPG" },
  { name: "Sofia Thomas", team: "Logistics Lead", image: "SOFIA_THOMAS.JPG" },
  { name: "Aayushi Hansalia", team: "Logistics", image: "AAYUSHI_HANSALIA.JPG" },
  { name: "Joel Philipose", team: "Logistics", image: "JOEL_PHILIPOSE.JPG" },
  { name: "Kaysan Amin", team: "Logistics", image: "KAYSAN_AMIN.JPG" },
  { name: "Nirmal Shah", team: "Logistics", image: "NIRMAL_SHAH.JPG" },
  { name: "Shobana Ravi", team: "Logistics", image: "SHOBANA_RAVI.JPG" },
  { name: "Sree Aatish Bommisetty", team: "Finance Lead", image: "SREE_AATISH_BOMMISETTY.JPG" },
  { name: "Anush Gudapuri", team: "Finance", image: "ANUSH_GUDAPURI.JPG" },
  { name: "Krishna Yadav", team: "Finance", image: "KRISHNA_YADAV.JPG" },
  { name: "Liana Forster", team: "Experience Lead", image: "LIANA_FORSTER.JPG" },
  { name: "Adhya Waikar", team: "Experience", image: "ADHYA_WAIKAR.JPG" },
  { name: "Akash Dasarraju", team: "Experience", image: "AKASH_DASSARAJU.JPG" },
  { name: "Soniya Jacob", team: "Experience", image: null },
  { name: "Keane Ferdinand", team: "Experience", image: "KEANE_FERDINAND.JPG" },
  { name: "Swayam Arora", team: "Experience", image: "SWAYAM_ARORA.JPG" },
  { name: "Sunay Shehaan", team: "Experience", image: "SUNAY_SHEHAAN.JPG" },
  { name: "Tien Phan", team: "Experience", image: "TIEN_PHAN.JPG" },
  { name: "Caleb Bae", team: "Tech Lead", image: "CALEB_BAE.JPG" },
  { name: "Jordan Joelson", team: "Tech", image: "JORDAN_JOELSON.JPG" },
  { name: "Anish Alle", team: "Tech", image: "ANISH_ALLE.JPG" },
  { name: "Arnav Vedula", team: "Tech", image: "ARNAV_VEDULA.JPG" },
  { name: "Ayro Escobar", team: "Tech", image: "AYRO_ESCOBAR.JPG" },
  { name: "Jagadeep Kalluri", team: "Tech", image: "JAGADEEP_KALLURI.jpeg" },
  { name: "Noel Varghese", team: "Tech", image: "NOEL_VARGHESE.JPG" },
  { name: "Sreevasan Sivasubramanian", team: "Tech", image: "SREEVASAN_SIVASUBRAMANIAN.JPG" },
  { name: "Tharun Sevvel", team: "Tech", image: "THARUN_SEVVEL.JPG" },
];
