export default [
  { name: "Adelaide (Addy) Dunning", team: "Director" },
  { name: "Kelly Zhou", team: "Director" },
  { name: "Daniel Kim", team: "Experience" },
  { name: "Reiki Hingorani", team: "Experience" },
  { name: "Alan Roybal", team: "Experience" },
  { name: "Veer Shah", team: "Experience" },
  { name: "Liana Forster", team: "Experience" },
  { name: "Sahas Sharma", team: "Experience" },
  { name: "Sunay Sheehan", team: "Experience" },
  { name: "Anwita Gudapuri", team: "Logistics" },
  { name: "Shreya Mekala", team: "Logistics" },
  { name: "Sahishnu Sagiraju", team: "Logistics" },
  { name: "Sofia Thomas", team: "Logistics" },
  { name: "Soumika Seelam", team: "Logistics" },
  { name: "Dhivyesh Prithiviraj", team: "Logistics" },
  { name: "Ridwan Amin", team: "Industry" },
  { name: "Sachi Hansalia", team: "Industry" },
  { name: "Bryan Caraman", team: "Industry" },
  { name: "John Luke", team: "Industry" },
  { name: "Abdala Aljewarane", team: "Industry" },
  { name: "Shraddha Subash", team: "Industry" },
  { name: "Nandini Paidesetty", team: "Industry" },
  { name: "Rayyan Waris", team: "Tech" },
  { name: "Wei Seng", team: "Tech" },
  { name: "Shaswat (Shaz) Kumar", team: "Tech" },
  { name: "Caleb Bae", team: "Tech" },
  { name: "Sreevasan Sivasubramanian", team: "Tech" },
  { name: "Ayro Escobar", team: "Tech" },
  { name: "Andrew Dmitrievsky", team: "Tech" },
  { name: "Abhiram Tadepalli", team: "Tech" },
  { name: "Jordan Tan", team: "Marketing" },
  { name: "Mitchell Vu", team: "Marketing" },
  { name: "Ann Jayan", team: "Marketing" },
  { name: "Sarah Jacob", team: "Marketing" },
  { name: "Fletcher Lauber", team: "Marketing" },
  { name: "Faith Kim", team: "Marketing" },
  { name: "Kavi Namburi", team: "Marketing" },
  { name: "Tien Phan", team: "Marketing" },
  { name: "Ayusha Timalsena", team: "Finance" },
  { name: "Sree Aastish Bommisetty", team: "Finance" },
  { name: "Leeza Paul", team: "Finance" },
];
